# Generated by Django 2.1.2 on 2018-10-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('user', models.ManyToManyField(blank=True, related_name='groups', to='users.Profile')),
            ],
        ),
    ]
