# Generated by Django 2.1.2 on 2018-10-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='user',
            new_name='profile',
        ),
    ]
