# Generated by Django 2.1.2 on 2018-10-29 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0003_auto_20181029_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='profiles',
        ),
        migrations.AddField(
            model_name='group',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='member_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
